apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: idxc-hpa
  namespace: <namespace>
spec:
  scaleTargetRef:
    apiVersion: enterprise.splunk.com/v2
    kind: IndexerCluster
    name: idxc
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
